name: monthly-update
on:
  # 手動実行ボタン
  workflow_dispatch:

  # 28〜31日の 23:30(JST) に毎日実行
  #   23:30 JST = 14:30 UTC → 30 14 ...
  schedule:
    - cron: '30 14 28-31 * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python update.py
      - run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add merged_list.csv
          git commit -m "auto update" || echo "no changes"
          git push
